CREATE DATABASE IF NOT EXISTS web
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'app'@'%' IDENTIFIED BY 'apppass';

GRANT ALL PRIVILEGES ON web.* TO 'app'@'%';

FLUSH PRIVILEGES;

USE web;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id            CHAR(32)     NOT NULL PRIMARY KEY,
  name          VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;
